

#ifndef FUN_H
#define FUN_H

#define DEN_SAMPLE2(NAME) NAME 
#define DEN_SAMPLE(NAME) DEN_SAMPLE2(NAME)


#define DEN_SAMPLE33(NAME) NAME ## _scaled_check
#define DEN_CHECK_SCALED(NAME) DEN_SAMPLE33(NAME)

#define DEN_SAMPLE3(NAME) NAME ## _scaled
#define DEN_SAMPLE_SCALED(NAME) DEN_SAMPLE3(NAME)

#define DEN_SAMPLE3_SYM(NAME) NAME ## _sym_scaled
#define DEN_SAMPLE_SYM_SCALED(NAME) DEN_SAMPLE3_SYM(NAME)




#define DEN_SAMPLE44(NAME) NAME ## _custom_check
#define DEN_CHECK_CUSTOM(NAME) DEN_SAMPLE44(NAME)

#define DEN_SAMPLE4(NAME) NAME ## _custom
#define DEN_SAMPLE_CUSTOM(NAME) DEN_SAMPLE4(NAME)

#define DEN_SAMPLE444(NAME) NAME ## _sym_custom
#define DEN_SAMPLE_SYM_CUSTOM(NAME) DEN_SAMPLE444(NAME)






#define DEN_TRUNC_NAV2(NAME) NAME ## _trunc_nav
#define DEN_TRUNC_NAV(NAME) DEN_TRUNC_NAV2(NAME)

#define DEN_TRUNC2(NAME) NAME ## _trunc
#define DEN_TRUNC(NAME) DEN_TRUNC2(NAME)

#endif
